### ISSUE TITLE
Is a port for micropython possible/planned?

### ISSUE THREAD

**Issue by sp4m4r** [DFRobot/DFRobot_GNSS#1]
Dears,

I bought the SKU-TEL0157 Gravity GNSS Positioning Module and it works like a charm with arduino code. However, I want to use it with micropython but to the best of my knowledge there is no code or workaround that works with the module. There is some micropython code for the Quectel L76K available from [Waveshare](https://www.waveshare.com/wiki/L76K_GPS_Module), but I can not do the magic to make it work for me.

So, is it possible or planned to get a driver for micropython?

Kind regards.

**Comment by 96liuzhixin** [comment]
Support is currently not planned, but may be supported in the future
