### ISSUE TITLE
Lat/Lon directions are swapped!

### ISSUE THREAD

**Issue by theGOTOguy** [DFRobot/DFRobot_GNSS#2]
This is an issue technically baked into the DFRobot GNSS/GPS device itself and not the drivers, but the issue needs to be ideally addressed in the firmware, or if not, it must be worked around in the drivers.

[This line of code](https://github.com/DFRobot/DFRobot_GNSS/blob/master/python/raspberrypi/DFRobot_GNSS.py#L165), which ostensibly reads latitude direction (N/S), instead returns the correct direction of longitude (E/W)!

On the other hand, [this line of code](https://github.com/DFRobot/DFRobot_GNSS/blob/master/python/raspberrypi/DFRobot_GNSS.py#L180), which likewise is supposed to read longitude direction (E/W), instead returns the correct direction of latitude (N/S)!

**Comment by 96liuzhixin** [comment]
Have been modified
