### ISSUE TITLE
重大錯誤：庫中的錯誤 - 緯度：東經，經度：北緯。

### ISSUE THREAD

**Issue by greenhouse69** [DFRobot/DFRobot_GNSS#4]
緯度只能是 0º 到 90º 北或 0º 到 90º 南（-90º），而經度只能是 0º 到 180º 東或 0º 到 180º 西（-180º）。
你們的庫定義緯度為東或西，而經度為北或南。這是完全不正確的！！！！！！

**Comment by 96liuzhixin** [comment]
Use the latest version to solve the longitude and latitude problem
